### ISSUE TITLE
Can't install package on macOS

### ISSUE THREAD

**Issue by magnusross** [wesselb/gpar#3]
Hi!

I'm trying to use GPAR for a project, but I'm having some trouble with installation. I'm on macOS 10.15.7, and have tried both the method in the docs, using make, and using pip like in the README. I have gcc and gfortran-5. Error message below (it is the same in both cases) :

ERROR: Command errored out with exit status 1:
   command: /Users/magnus/miniconda3/bin/python /Users/magnus/miniconda3/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /private/tmp/pip-build-env-b2vyz6fh/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=41.0' 'wheel>=0.33' 'numpy>=1.16' 'cython>=0.29'
       cwd: None
  Complete output (42 lines):
  Traceback (most recent call last):
    File "/Users/magnus/miniconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
      "__main__", mod_spec)
    File "/Users/magnus/miniconda3/lib/python3.7/runpy.py", line 85, in _run_code
      exec(code, run_globals)
    File "/Users/magnus/miniconda3/lib/python3.7/site-packages/pip/__main__.py", line 26, in <module>
      sys.exit(_main())
    File "/Users/magnus/miniconda3/lib/python3.7/site-packages/pip/_internal/cli/main.py", line 73, in main
      command = create_command(cmd_name, isolated=("--isolated" in cmd_args))
    File "/Users/magnus/miniconda3/lib/python3.7/site-packages/pip/_internal/commands/__init__.py", line 105, in create_command
      module = importlib.import_module(module_path)
    File "/Users/magnus/miniconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module
      return _bootstrap._gcd_import(name[level:], package, level)
    File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
    File "<frozen importlib._bootstrap>", line 983, in _find_and_load
    File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
    File "<frozen importlib._bootstrap_external>", line 728, in exec_module
    File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
    File "/Users/magnus/miniconda3/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 17, in <module>
      from pip._internal.cli.req_command import RequirementCommand, with_cleanup
    File "/Users/magnus/miniconda3/lib/python3.7/site-packages/pip/_internal/cli/req_command.py", line 18, in <module>
      from pip._internal.index.collector import LinkCollector
    File "/Users/magnus/miniconda3/lib/python3.7/site-packages/pip/_internal/index/collector.py", line 14, in <module>
      from pip._vendor import html5lib, requests
    File "/Users/magnus/miniconda3/lib/python3.7/site-packages/pip/_vendor/requests/__init__.py", line 125, in <module>
      from . import utils
    File "/Users/magnus/miniconda3/lib/python3.7/site-packages/pip/_vendor/requests/utils.py", line 25, in <module>
      from . import certs
    File "/Users/magnus/miniconda3/lib/python3.7/site-packages/pip/_vendor/requests/certs.py", line 15, in <module>
      from pip._vendor.certifi import where
    File "/Users/magnus/miniconda3/lib/python3.7/site-packages/pip/_vendor/certifi/__init__.py", line 1, in <module>
      from .core import contents, where
    File "/Users/magnus/miniconda3/lib/python3.7/site-packages/pip/_vendor/certifi/core.py", line 12, in <module>
      from importlib.resources import path as get_path, read_text
    File "/Users/magnus/miniconda3/lib/python3.7/importlib/resources.py", line 11, in <module>
      from typing import Iterable, Iterator, Optional, Set, Union   # noqa: F401
    File "/Users/magnus/miniconda3/lib/python3.7/site-packages/typing.py", line 1373, in <module>
      class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):
    File "/Users/magnus/miniconda3/lib/python3.7/site-packages/typing.py", line 1024, in __new__
      self._abc_registry = extra._abc_registry
  AttributeError: type object 'Callable' has no attribute '_abc_registry'
  ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/magnus/miniconda3/bin/python /Users/magnus/miniconda3/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /private/tmp/pip-build-env-b2vyz6fh/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=41.0' 'wheel>=0.33' 'numpy>=1.16' 'cython>=0.29' Check the logs for full command output.

Cheers!

**Comment by wesselb** [comment]
Hey @magnusross! Thanks for opening an issue.

Some Googling [reveals](https://stackoverflow.com/questions/55833509/attributeerror-type-object-callable-has-no-attribute-abc-registry) that this might be an issue with the package `typing` for Python 3.7. Are you able to run this on 3.6 or 3.8?

Moreover, I am currently in the process of updating the GPAR package to account for updates in its dependencies. At the moment, the package might not work. I hope to have this resolved either this evening or tomorrow. I will update you here once this is done.

**Comment by magnusross** [comment]
Thanks for getting back to me so quickly, sorry for the horrible formatting mess above, I didn't realise!

Good news, I tried it in 3.8 and it installs, however I get another error on import, form the stheno package:

`>>> import gpar
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/magnus/miniconda3/envs/pytorch/lib/python3.8/site-packages/gpar/__init__.py", line 2, in <module>
    from .regression import *
  File "/Users/magnus/miniconda3/envs/pytorch/lib/python3.8/site-packages/gpar/regression.py", line 7, in <module>
    from stheno.torch import Graph, GP, EQ, RQ, Delta, Linear, ZeroKernel
ImportError: cannot import name 'Graph' from 'stheno.torch' (/Users/magnus/miniconda3/envs/pytorch/lib/python3.8/site-packages/stheno/torch.py)`

**Comment by wesselb** [comment]
No problem at all!

Yes, the error you are now getting are because the dependencies of the package are out of date. Sorry about that. I'm currently working on it and hope to have that fixed soon.

**Comment by wesselb** [comment]
@magnusross, could you try updating to `0.2.0` (`pip install --upgrade gpar`) to see if that works for you?

**Comment by magnusross** [comment]
Just tried and the import works, haven't tried on data but seems like it's resolved.

Thanks for your help, I appreciate it!

**Comment by wesselb** [comment]
Great to hear! Do let me know if you run into any other issues.
